// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQXBKIcwFMTdqITmW35If6RbLGzWC66C8',
    appId: '1:121104576212:web:50dcf7250a7d82eb0b9541',
    messagingSenderId: '121104576212',
    projectId: 'perum-app-d9b27',
    authDomain: 'perum-app-d9b27.firebaseapp.com',
    storageBucket: 'perum-app-d9b27.firebasestorage.app',
    measurementId: 'G-03KFEEG751',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3VaSOjbwZPIcdKn-22YzrPxRYJFuLSBg',
    appId: '1:121104576212:android:893869c5fb202c1c0b9541',
    messagingSenderId: '121104576212',
    projectId: 'perum-app-d9b27',
    storageBucket: 'perum-app-d9b27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIClb9NdH2GMFtiGbvsn0xB2VUuOCBlNI',
    appId: '1:121104576212:ios:1c810740c9d38f890b9541',
    messagingSenderId: '121104576212',
    projectId: 'perum-app-d9b27',
    storageBucket: 'perum-app-d9b27.firebasestorage.app',
    iosBundleId: 'com.example.perumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIClb9NdH2GMFtiGbvsn0xB2VUuOCBlNI',
    appId: '1:121104576212:ios:1c810740c9d38f890b9541',
    messagingSenderId: '121104576212',
    projectId: 'perum-app-d9b27',
    storageBucket: 'perum-app-d9b27.firebasestorage.app',
    iosBundleId: 'com.example.perumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQXBKIcwFMTdqITmW35If6RbLGzWC66C8',
    appId: '1:121104576212:web:50dcf7250a7d82eb0b9541',
    messagingSenderId: '121104576212',
    projectId: 'perum-app-d9b27',
    authDomain: 'perum-app-d9b27.firebaseapp.com',
    storageBucket: 'perum-app-d9b27.firebasestorage.app',
    measurementId: 'G-03KFEEG751',
  );

}