// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqMBGE-vsofLt7hBxbiHep1KHZI5RljNY',
    appId: '1:1005777077790:web:75948fcc6495fc4644500f',
    messagingSenderId: '1005777077790',
    projectId: 'ivan-app-29345',
    authDomain: 'ivan-app-29345.firebaseapp.com',
    storageBucket: 'ivan-app-29345.firebasestorage.app',
    measurementId: 'G-K4TJ4TE54W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-m07hb-aEhrIQqaS-Zuivfpr9XiAhLXY',
    appId: '1:1005777077790:android:f7b82774cd72843044500f',
    messagingSenderId: '1005777077790',
    projectId: 'ivan-app-29345',
    storageBucket: 'ivan-app-29345.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXg-0isY2ty6A5LdQD-i-3ePAP8kpjNvU',
    appId: '1:1005777077790:ios:d700a60988a5bff044500f',
    messagingSenderId: '1005777077790',
    projectId: 'ivan-app-29345',
    storageBucket: 'ivan-app-29345.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXg-0isY2ty6A5LdQD-i-3ePAP8kpjNvU',
    appId: '1:1005777077790:ios:d700a60988a5bff044500f',
    messagingSenderId: '1005777077790',
    projectId: 'ivan-app-29345',
    storageBucket: 'ivan-app-29345.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqMBGE-vsofLt7hBxbiHep1KHZI5RljNY',
    appId: '1:1005777077790:web:eaa65d42899ac33744500f',
    messagingSenderId: '1005777077790',
    projectId: 'ivan-app-29345',
    authDomain: 'ivan-app-29345.firebaseapp.com',
    storageBucket: 'ivan-app-29345.firebasestorage.app',
    measurementId: 'G-88ZK2KB4HD',
  );
}
